gazebo:
  delay: 0.009
  imus:
    base_imu:
      frame_id: torso
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
  contacts: [ "ll_faa", "lr_faa" ]
